<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-06T13:05:01 BDT" name="Default suite" finished-at="2023-06-06T13:06:37 BDT" duration-ms="96121">
    <groups>
    </groups>
    <test started-at="2023-06-06T13:05:01 BDT" name="Default test" finished-at="2023-06-06T13:06:37 BDT" duration-ms="96121">
      <class name="Package1.BaseClass">
        <test-method is-config="true" signature="geturl()[pri:0, instance:Package1.BaseClass@4c583ecf]" started-at="2023-06-06T13:05:01 BDT" name="geturl" finished-at="2023-06-06T13:05:09 BDT" duration-ms="7928" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- geturl -->
        <test-method signature="Login()[pri:1, instance:Package1.BaseClass@4c583ecf]" started-at="2023-06-06T13:05:09 BDT" name="Login" finished-at="2023-06-06T13:05:19 BDT" duration-ms="10855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="Newcontact()[pri:2, instance:Package1.BaseClass@4c583ecf]" started-at="2023-06-06T13:05:19 BDT" name="Newcontact" finished-at="2023-06-06T13:05:33 BDT" duration-ms="13191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Newcontact -->
        <test-method signature="AddressBookInfo()[pri:3, instance:Package1.BaseClass@4c583ecf]" started-at="2023-06-06T13:05:33 BDT" name="AddressBookInfo" finished-at="2023-06-06T13:06:08 BDT" duration-ms="34943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddressBookInfo -->
        <test-method signature="View()[pri:4, instance:Package1.BaseClass@4c583ecf]" started-at="2023-06-06T13:06:08 BDT" name="View" finished-at="2023-06-06T13:06:37 BDT" duration-ms="29097" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Result not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Result not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at Package1.BaseClass.View(BaseClass.java:240)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- View -->
      </class> <!-- Package1.BaseClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
